"""macros tables

Revision ID: 636b7fb55d98
Revises: 2655de3f8836
Create Date: 2024-06-29 16:12:42.557789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '636b7fb55d98'
down_revision: Union[str, None] = '2655de3f8836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macros_tracker',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('user', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein', sa.Integer(), nullable=False),
    sa.Column('carbs', sa.Integer(), nullable=False),
    sa.Column('fats', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('target_macros',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('user', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein', sa.Integer(), nullable=False),
    sa.Column('carbs', sa.Integer(), nullable=False),
    sa.Column('fats', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('target_macros')
    op.drop_table('macros_tracker')
    # ### end Alembic commands ###
